GenMed/GenMed/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'),namespace='home')),
    path('shop/', include(('shop.urls', 'shop'),namespace='shop')),
    path('medicine/', include(('medicine.urls', 'medicine'),namespace='medicine')),
]

GenMed/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.logIn, name='logIn'),
    path('logout/',views.logOut, name='logOut'),
    path('register/',views.register, name='register'),
    path('createshop/',views.createshop, name='create_shop'),
    path('sqlerror/', views.sqlerror, name = 'sqlerror')
]

GenMed/shop/urls.py
from django.urls import path
from . import views
from .feeds import ShopCommentFeed

urlpatterns = [
    path('dashboard/',views.dashboard, name='dashboard'),
    path('updatestock/',views.update_stock, name='update_stock'),
    path('addmed/',views.add_med, name='add_med'),
    path('updatemed/',views.update_med, name='update_med'),
    path('search/', views.search, name='search'),
    path('profile/<int:shop_id>',views.profile, name='profile'),
    path('curstock/',views.cur_stock, name='cur_stock'),
    path('updateinfo/',views.update_info, name='update_info'),
    path('updatecord/', views.update_cord, name='update_cord'),
    path('updatelicense/', views.update_license, name='update_license'),
    path('license/', views.license, name='license'),
    path('home/', views.home, name='home'),
    path('shopcomments/', ShopCommentFeed(), name='shopcomments'),
    path('feeds/<int:comment_no>/', views.feeds, name='feeds'),
    path('comment/', views.comment, name='comment'),
    path('map/', views.map, name='map_test')
]

GenMed/templates/baseheader.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GenMed-Project</title>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans|Ubuntu" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">    
    <link rel="stylesheet" type="text/css" href="{% static 'baseheader.css' %}">
    
    {%  block head %}
    {% endblock %}


</head>

<body>

    <nav class="navbar navbar-expand-md sticky-top bg-dark" style="padding-bottom:0">
        <!-- Brand-->
        <a href="#" class="navbar-brand" id="home-link">GenMed</a>
        
        <!--Toggle Button-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#base-nav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--Links-->
        <div class="collapse navbar-collapse" id="base-nav">
            <ul class="navbar-nav navbar-left" id='left-nav'>
                <li class="nav-item"><a href="{% url 'home:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'shop:home' %}" class="nav-link">Shop</a></li>
                <li class="nav-item"><a href="{% url 'medicine:home' %}" class="nav-link">Medicines</a></li>
            </ul>
        </div>
        <div>
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav navbar-right" id='right-nav'>
                    <li class="nav-item"><a href="#" class="nav-link">Hello {{ request.user.username }}</a></li>
                    <li class="nav-item"><a href="{% url 'shop:dashboard' %}" class="nav-link">Profile</a></li>
                    <li class="nav-item"><a href="{% url 'home:logOut' %}" class="nav-link">Logout</a></li>
                </ul>
            {% else %}
                <ul class="navbar-nav navbar-right" id='right-nav'>
                    <li class="nav-item"><a href="{% url 'home:logIn' %}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{% url 'home:register' %}" class="nav-link">Signup</a></li>
                </ul>
            {% endif %}
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <footer>
        <ul class="list-inline social-icon"> 
            <li>
                <a title="Github" href="https://github.com/pegasus-lynx/GenMed-Project.git" target="blank">
                    <i class="fa fa-github"></i>
                </a>
            </li>
            <li>
                <a title="Facebook" href="#" target="blank">
                    <i class="fa fa-facebook"></i>
                </a>
            </li>  
            <li>
                <a Title="Mail" href="#">
                    <i class="fa fa-envelope-o"></i>
                </a>
            </li> 
        </ul>
    </footer>

<script src="{% static 'baseheader.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>