GenMed/GenMed/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'),namespace='home')),
    path('shop/', include(('shop.urls', 'shop'),namespace='shop')),
    path('medicine/', include(('medicine.urls', 'medicine'),namespace='medicine')),
]

GenMed/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.logIn, name='logIn'),
    path('logout/',views.logOut, name='logOut'),
    path('register/',views.register, name='register'),
    path('createshop/',views.createshop, name='create_shop'),
    path('sqlerror/', views.sqlerror, name = 'sqlerror')
]

GenMed/medicine/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('info',views.query_medinfo, name='info'),
    path('avail',views.query_medavail, name='avail'),
]

GenMed/shop/urls.py
from django.urls import path
from . import views
from .feeds import ShopCommentFeed

urlpatterns = [
    path('dashboard/',views.dashboard, name='dashboard'),
    path('updatestock/',views.update_stock, name='update_stock'),
    path('addmed/',views.add_med, name='add_med'),
    path('updatemed/',views.update_med, name='update_med'),
    path('search/', views.search, name='search'),
    path('profile/<int:shop_id>',views.profile, name='profile'),
    path('curstock/',views.cur_stock, name='cur_stock'),
    path('updateinfo/',views.update_info, name='update_info'),
    path('updatecord/', views.update_cord, name='update_cord'),
    path('updatelicense/', views.update_license, name='update_license'),
    path('license/', views.license, name='license'),
    path('home/', views.home, name='home'),
    path('shopcomments/', ShopCommentFeed(), name='shopcomments'),
    path('feeds/<int:comment_no>/', views.feeds, name='feeds'),
    path('comment/', views.comment, name='comment'),
    path('map/', views.map, name='map_test')
]

GenMed/home/models.py
from django.db import models

# Create your models here.

GenMed/medicine/models.py
from django.db import models

# Create your models here.

class MedInfo(models.Model):
    med_id = models.AutoField(primary_key=True)
    gen_name = models.CharField(unique=True, max_length=64, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'med_info'

class ComName(models.Model):
    med = models.ForeignKey('MedInfo', models.DO_NOTHING, blank=True, null=True)
    company_name = models.CharField(max_length=64, blank=True, null=True)
    custom_name = models.CharField(primary_key=True, max_length=64)

    class Meta:
        managed = False
        db_table = 'com_name'

class Avail(models.Model):
    med_id = models.IntegerField(primary_key=True)
    shop_id = models.IntegerField()
    units = models.IntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    mfg_date = models.DateField(blank=True, null=True)
    exp_date = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'avail'
        unique_together = (('med_id', 'shop_id'),)

class Extra(models.Model):
    med_id = models.IntegerField(primary_key=True)
    shop_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'extra'
        unique_together = (('med_id', 'shop_id'),)

GenMed/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
import MySQLdb

#this file includes function for sql queries used by multiple views.
from GenMed.mysql import *

def is_valid_email(email):
    return True

# View for displaying the homepage in the home app
def home(request):
    context = {}
    return render(request, 'home/home.html', context)

def sqlerror(request):
    return render(request, 'home/sqlerror.html', context = {})

# View for logging in 
def logIn(request):
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    db=connect()
    c=db.cursor()
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            print('1.',str(user))
            return redirect(reverse('shop:dashboard'))
        else:    
            context = { 'error':True }
            return render(request, 'home/loginpage.html', context)
    else:
        get_userlist(request,c)
        context = { 'error':False }
        return render(request, 'home/loginpage.html', context)

# View for logging out
def logOut(request):
    try:
        logout(request)
    except ValueError:
        pass
    return redirect(reverse('home:home'))

# View for registering
def register(request):
    db=connection
    c=db.cursor()
    userlist = get_userlist(request,c)
    if request.method=='POST':
        q = request.POST.dict()
        print(q)
        if q['password'] != q['cnf_password']:
            err = "Passwords don't match"
            return render(request, 'home/register.html', context= { 'err': err })
        elif not is_valid_email(q['email']):
            err = "Invalid email"
            return render(request, 'home/register.html', context= { 'err': err })
        elif q['username'] in userlist:
            err = "Username already taken"
            return render(request, 'home/register.html', context= { 'err': err })
        else:
            c.execute(
                """ INSERT into shop(username,email,passwd) 
                    values (%s,%s,%s) """,
                    (q['username'],q['email'],q['password'])
            )
            db.commit()
            p = User(username=q['username'],password=q['password'])
            p.save()
            login(request,p)
            return render(request, 'home/createshop.html', context = {})
    else:
        context = { 'userlist':userlist }
        return render(request, 'home/register.html', context)

# View for creating a shop object
@login_required
def createshop(request):
    db=connect()
    c=db.cursor()
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    if request.user.is_authenticated:
        if request.method == 'POST':
            q = request.POST.dict()
            shop_id = get_max_shopid(request,c)+1
            user_id = get_userid_by_name(request,c)
            
            # insert into shop_info
            c.execute(
                """ INSERT into shop_info(shop_id,name,owner_name,
                    mob_no,alt_no,license,user_id) values(%s,%s,%s,%s,%s,%s,%s) """,
                    (shop_id,q['shop_name'],q['owner_name'],
                        q['mob_no'],q['alt_no'],q['license'],user_id)
            )
            db.commit()
            
            # insert into the pharmacist table the pharmacist details
            c.execute(
                """ INSERT into ph_detail(name,deg,college)
                    values(%s,%s,%s) """,
                    (q['ph_name'],q['ph_deg'],q['ph_college'])
            )
            db.commit()

            # get the ph_id of the saved pharmacist
            c.execute(
                """ SELECT ph_id
                    from ph_detail
                    where name = %s and deg = %s and college = %s """,
                    (q['ph_name'],q['ph_deg'],q['ph_college'])
            )
            
            ph_id=str(c.fetchone()[0])
            
            # inserts information in the shop_license table
            c.execute(
                """ INSERT into shop_license(shop_id,ph_id,license,dr_license_type,dr_license_no)
                    values(%s,%s,%s,%s,%s) """,
                    (shop_id,ph_id,q['license'],q['drug_license_type'],q['drug_license'])
            )
            db.commit()

            # insert into the shop_location table
            c.execute(
                """ INSERT into shop_loc(shop_id,lat,lon,
                    state,district,city) values(%s,%s,%s,%s,%s,%s) """,
                    (shop_id,q['lat'],q['lon'],
                     q['state'],q['district'],q['city'])
            )
            db.commit()
            return redirect(reverse('shop:dashboard'))
        else:
            context = {}
            return render(request, 'home/createshop.html', context)
    else:
        context = {}
        return render(request, 'home/createshop.html', context)

GenMed/medicine/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from GenMed.mysql import *
import MySQLdb

# View for displaying the homepage of the medicine app
def home(request):
    context = {}
    return render(request, 'medicine/home.html', context)

# Displays the medicine information of the searched medicine
def query_medinfo(request):
    db=connect()
    c=db.cursor()
    context = {}
    get_query = 0
    if request.method=="GET":
        get_query = 1
        med = request.GET.get('med-name')
        c.execute(
            """ SELECT med_id from com_name where
                custom_name = %s """,
                (med,)
        )
        med_id = c.fetchone()
        if med_id  is None:
            context = { "get_query":get_query }
        else:
            c.execute(
                """ SELECT gen_name from med_info where
                    med_id = %s """,
                    (med_id,)
            )
            gen_name= c.fetchone()

            c.execute(
                """ select custom_name, company_name from com_name
                    where med_id = %s """,
                    (med_id,)
            )
            common_name = list(c.fetchall())
            context = { 'get_query':get_query, 'gen_name':gen_name[0], 'common_name':common_name, }
    elif request.method == 'POST':
        q = request.POST.dict()
        med_id = get_medid(request,c,q['gen_name'])

        # inserts the common name to the com_name
        c.execute(
            """ insert into com_name(med_id,company_name,custom_name) 
                values(%s,%s,%s)""" ,
                (med_id,q['company_name'],q['custom_name'])
        )
        db.commit()

        # selects the custom names of the drug using the med_id
        c.execute(
            """ select custom_name, company_name from com_name
                where med_id = %s """,
                (med_id,)
        )
        common_name = list(c.fetchall()) 
        context = { 'get_query':1, 'gen_name':q['gen_name'], 'common_name':common_name, }
        return render(request, 'medicine/info.html', context)
    else:
        context = { 'get_query':False, }

    return render(request, 'medicine/info.html', context)

# Displays the information about the medicine that where it is available
def query_medavail(request):
    db=connect()
    c=db.cursor()
    q=db.cursor()
    if request.method=='GET':
        med = request.GET.get('med-name')
        if med is not None:
            med_id = get_med(request,c,med)
        else:
            med_id = None
        if med_id is None and med is None:
            context = { "get_query":False}
        elif med_id is None:
            context = { "get_query":True, 'name':med }
        else:
            med_id = med_id[0]
            shops = get_shops_by_med(request,c,med_id)
            shop_ids = list(shops.keys())
            loc = {}
            for i in shop_ids:
                loc[i]=get_shopcord(c,i)
                loc[i]+=get_city(c,i)

                
            print(loc[i])
            context = {'get_query':True, 'med_id':med_id, 'shops':shops, 'loc':loc}
    else:
        context = { "get_query":False }
    return render(request, 'medicine/avail.html', context)

GenMed/templates/medicine/avail.html
{% extends 'medicine/medheader.html' %}

{% load customtags %}
{% load static %}
{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'medicine/avail.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
{% endblock %}

{% block body_2 %}
    <div class='container'>
        {% if get_query %}
            {%if med_id != None  %}
                <section id="map">
                </section>    
                <section id="shop-sec">
                    <ul id='list'>
                        <li class='cards' id='head'>
                            <span class='rowhead'>Shop Name</span>
                            <span class='rowhead'>Price</span>
                            <span class='rowhead'>Units</span>
                            <span class='rowhead'>City</span>
                        </li>
                        {% for key,value in shops.items %}
                            <li class='cards'>
                                <span class='count'>{{ forloop.counter }}</span>
                                {% for col in value %}
                                    <span class='col{{ forloop.counter }}'>{{ col }}</span>
                                {% endfor %}
                                <span class='col4'>{{ loc|getcity:key }}</span>
                                <span class='loca'><a href="{% url 'shop:profile' key %}"><i class="fa fa-map" aria-hidden="true"></i></a></span>
                            </li>
                        {% endfor %}
                    </ul>
                </section>

            {% else %}
                <section id="not_found">
                    <h1>Sorry</h1>
                    <hr>
                    <p>We could not find any matching results for {{ name }} in our databases.</p>
                </section>
            {% endif %}
        {% endif %}
    </div>
    <script type='text/javascript'>
        function GetMap()
        {
            var map = new Microsoft.Maps.Map('#myMap', {
                credentials: 'Your Bing Maps Key',
                center: new Microsoft.Maps.Location(51.50632, -0.12714),
                mapTypeId: Microsoft.Maps.MapTypeId.aerial,
                zoom: 10
            });
    
            //Add your post map load code here.
        }
    </script>

{% endblock %}

GenMed/templates/medicine/home.html
{% extends 'medicine/medheader.html' %}

{% load static %}
{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'medicine/home.css' %}">
{% endblock %}

{% block body_2 %}

    <section id="gen-med-info">

        <div class="para">
            <h1>What are generic drugs?</h1>
            <p>A generic drug is a medication created to be the same as an already 
            marketed brand-name drug in dosage form, safety, strength, route of 
            administration, quality, performance characteristics, and intended use. 
            These similarities help to demonstrate bioequivalence, which means 
            that a generic medicine works in the same way and provides the same
            clinical benefit as its brand-name version. In other words, you can 
            take a generic medicine as an equal substitute for its brand-name counterpart.</p>
        </div>

        <div class='para'>
            <h1>Do generic medicines work the same as brand-name medicines?</h1>
            <p>Yes. Any generic medicine modeled after a brand-name medicine must perform the same 
            in the body as the brand-name medicine. This standard applies to all generic medicines. 
            A generic medicine is the same as a brand-name medicine in dosage, safety, effectiveness, 
            strength, stability, and quality, as well as in the way it is taken and the way it should 
            be used. Generic medicines use the same active ingredients as brand-name medicines and work the same way, 
            so they have the same risks and benefits as the brand-name medicines. The FDA Generic Drugs 
            Program conducts a rigorous review to make certain generic medicines meet these standards,
            in addition to conducting 3,500 inspections of manufacturing plants a year and monitoring 
            drug safety after the generic medicine has been approved and brought to market.
            <br><br>
            It is important to note that there will always be a slight, 
            but not medically important, level of natural variability—just as there is for 
            one batch of brand-name medicine compared with the next batch of brand-name product. This variability 
            can and does occur during manufacturing, for both brand-name and generic medicines. When a medicine, 
            generic or brand-name, is mass produced, very small variations in purity, size, strength, and other 
            parameters are permitted. FDA limits how much variability is acceptable.</p>
        </div>
    </section>
{% endblock %}

GenMed/templates/medicine/info.html
{% extends 'medicine/medheader.html' %}

{% load static %}
{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'medicine/info.css' %}">
{% endblock %}

{% block body_2 %}

    <section id="search-result">
    {% if gen_name %}
        <h1>{{ gen_name }}</h1>
        <hr>
        <h4>General Names</h4>

        <table class="col-lg-10">
            <tr>
                <th class="col1"> Drug Name</th>
                <th class="col2"> Company Name  </th>
            </tr>
            {% for row in common_name %}
                <tr>
                    {% for col in row %}
                        <td class="col{{ forloop.counter }}">{{ col }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            {% if user.is_authenticated %}
                <tr id='addrow'>
                    <form action="{% url 'medicine:info' %}" method="post" id='add'>
                        {% csrf_token %}
                        <td><input type="text" placeholder="Drug Name..." id="" name='custom_name'></td>
                        <td><input type="text" placeholder="Company Name..." id="" name='company_name'></td>
                        <input type="hidden" name="gen_name" value="{{ gen_name }}">
                    </form>
                </tr>
            {% endif %}
        </table>
        {% if user.is_authenticated %}
            <button onclick=addField() id='addBtn' class='inp' >Add Field</button>
            <button id='subBtn' class='inp' onclick=addName()>Add</button>
            <button id='cancelBtn' class='inp' onclick=cancelAdd()>Cancel</button>
        {% endif %}
    {% endif %}
    </section>

    <script src="{% static 'medicine/info.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
{% endblock %}

GenMed/templates/medicine/medheader.html
{% extends 'baseheader.html' %}

{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'medicine/medheader.css' %}">

    {% block head_2 %}
    {% endblock %}

{% endblock %}

{% block body %}
    <header>
        <div class="bg-image">
            <h1>Search the medicine here</h1>
            <form action="" method="get" autocomplete="off" id='search'>
                <p><input type="text" name="med-name" id="text-box" placeholder="Search..." 
                    onfocus="this.removeAttribute('placeholder')" onblur="this.setAttribute('placeholder','Search...')"></p>
                <p>
                    <input type="submit" name="info" value="Get Info" class="search-button" onclick=getInfo()>
                    <input type="submit" name="avail" value="Get Avail" class="search-button" onclick=getAvail()>
                </p>
            </form>
        </div>
    </header>

    <div class='container' id="main">    
        {% block body_2 %}
        {% endblock %}

        <script>
            function getInfo() {
                $('#search').attr('action',"{% url 'medicine:info' %}")
                $('#search').submit()
            }

            function getAvail() {
                $('#search').attr('action',"{% url 'medicine:avail' %}")
                $('#search').submit()
            }
        </script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>    
    </div>
    
{% endblock %}