GenMed/GenMed/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'),namespace='home')),
    path('shop/', include(('shop.urls', 'shop'),namespace='shop')),
    path('medicine/', include(('medicine.urls', 'medicine'),namespace='medicine')),
]

GenMed/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.logIn, name='logIn'),
    path('logout/',views.logOut, name='logOut'),
    path('register/',views.register, name='register'),
    path('createshop/',views.createshop, name='create_shop'),
    path('sqlerror/', views.sqlerror, name = 'sqlerror')
]

GenMed/shop/urls.py
from django.urls import path
from . import views
from .feeds import ShopCommentFeed

urlpatterns = [
    path('dashboard/',views.dashboard, name='dashboard'),
    path('updatestock/',views.update_stock, name='update_stock'),
    path('addmed/',views.add_med, name='add_med'),
    path('updatemed/',views.update_med, name='update_med'),
    path('search/', views.search, name='search'),
    path('profile/<int:shop_id>',views.profile, name='profile'),
    path('curstock/',views.cur_stock, name='cur_stock'),
    path('updateinfo/',views.update_info, name='update_info'),
    path('updatecord/', views.update_cord, name='update_cord'),
    path('updatelicense/', views.update_license, name='update_license'),
    path('license/', views.license, name='license'),
    path('home/', views.home, name='home'),
    path('shopcomments/', ShopCommentFeed(), name='shopcomments'),
    path('feeds/<int:comment_no>/', views.feeds, name='feeds'),
    path('comment/', views.comment, name='comment'),
    path('map/', views.map, name='map_test')
]

GenMed/home/models.py
from django.db import models

# Create your models here.

GenMed/shop/models.py
from django.db import models


class Comment(models.Model):
    comment_no = models.AutoField(primary_key = True)
    title = models.CharField(max_length=100)
    shop_id = models.IntegerField(default = 0)
    text = models.CharField(max_length = 500)

GenMed/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
import MySQLdb

#this file includes function for sql queries used by multiple views.
from GenMed.mysql import *

def is_valid_email(email):
    return True

# View for displaying the homepage in the home app
def home(request):
    context = {}
    return render(request, 'home/home.html', context)

def sqlerror(request):
    return render(request, 'home/sqlerror.html', context = {})

# View for logging in 
def logIn(request):
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    db=connect()
    c=db.cursor()
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            print('1.',str(user))
            return redirect(reverse('shop:dashboard'))
        else:    
            context = { 'error':True }
            return render(request, 'home/loginpage.html', context)
    else:
        get_userlist(request,c)
        context = { 'error':False }
        return render(request, 'home/loginpage.html', context)

# View for logging out
def logOut(request):
    try:
        logout(request)
    except ValueError:
        pass
    return redirect(reverse('home:home'))

# View for registering
def register(request):
    db=connection
    c=db.cursor()
    userlist = get_userlist(request,c)
    if request.method=='POST':
        q = request.POST.dict()
        print(q)
        if q['password'] != q['cnf_password']:
            err = "Passwords don't match"
            return render(request, 'home/register.html', context= { 'err': err })
        elif not is_valid_email(q['email']):
            err = "Invalid email"
            return render(request, 'home/register.html', context= { 'err': err })
        elif q['username'] in userlist:
            err = "Username already taken"
            return render(request, 'home/register.html', context= { 'err': err })
        else:
            c.execute(
                """ INSERT into shop(username,email,passwd) 
                    values (%s,%s,%s) """,
                    (q['username'],q['email'],q['password'])
            )
            db.commit()
            p = User(username=q['username'],password=q['password'])
            p.save()
            login(request,p)
            return render(request, 'home/createshop.html', context = {})
    else:
        context = { 'userlist':userlist }
        return render(request, 'home/register.html', context)

# View for creating a shop object
@login_required
def createshop(request):
    db=connect()
    c=db.cursor()
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    if request.user.is_authenticated:
        if request.method == 'POST':
            q = request.POST.dict()
            shop_id = get_max_shopid(request,c)+1
            user_id = get_userid_by_name(request,c)
            
            # insert into shop_info
            c.execute(
                """ INSERT into shop_info(shop_id,name,owner_name,
                    mob_no,alt_no,license,user_id) values(%s,%s,%s,%s,%s,%s,%s) """,
                    (shop_id,q['shop_name'],q['owner_name'],
                        q['mob_no'],q['alt_no'],q['license'],user_id)
            )
            db.commit()
            
            # insert into the pharmacist table the pharmacist details
            c.execute(
                """ INSERT into ph_detail(name,deg,college)
                    values(%s,%s,%s) """,
                    (q['ph_name'],q['ph_deg'],q['ph_college'])
            )
            db.commit()

            # get the ph_id of the saved pharmacist
            c.execute(
                """ SELECT ph_id
                    from ph_detail
                    where name = %s and deg = %s and college = %s """,
                    (q['ph_name'],q['ph_deg'],q['ph_college'])
            )
            
            ph_id=str(c.fetchone()[0])
            
            # inserts information in the shop_license table
            c.execute(
                """ INSERT into shop_license(shop_id,ph_id,license,dr_license_type,dr_license_no)
                    values(%s,%s,%s,%s,%s) """,
                    (shop_id,ph_id,q['license'],q['drug_license_type'],q['drug_license'])
            )
            db.commit()

            # insert into the shop_location table
            c.execute(
                """ INSERT into shop_loc(shop_id,lat,lon,
                    state,district,city) values(%s,%s,%s,%s,%s,%s) """,
                    (shop_id,q['lat'],q['lon'],
                     q['state'],q['district'],q['city'])
            )
            db.commit()
            return redirect(reverse('shop:dashboard'))
        else:
            context = {}
            return render(request, 'home/createshop.html', context)
    else:
        context = {}
        return render(request, 'home/createshop.html', context)

GenMed/shop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import Comment
from GenMed.mysql import *
import MySQLdb

def getCenter(shops):
    center = { 'lat':0, 'lon':0 }
    if len(shops)==0:
        return center
    for shop in shops:
        center['lat'] += shop['lat']
        center['lon'] += shop['lon']

    center['lat'] /= len(shops)
    center['lon'] /= len(shops)
    return center

# Displays the homepage in the shop
def home(request):
    return render(request, 'shop/home.html', context = {})

# Displays the dashboard to the shop_owners from where they can access any records
def dashboard(request):   
    if request.user.is_authenticated:
        db=connect()
        c=db.cursor()

        shop_id = get_shopid(request,c)
        shop_info = get_shopinfo(request,c,shop_id)
        shop_loc = get_shoploc(request,c,shop_id)

        print('shop_id',shop_id)
        print('shop_loc',shop_loc)
        print('shop_info',shop_info)

        context = {'shop_id':shop_id , 'shop_loc':shop_loc, 'shop_info':shop_info}
        return render(request, 'shop/dashboard.html', context)
    else:
        context = {}
        return render(request, 'home/loginpage.html', context)    

# displays the profile page to the consumers including their owner, contact detail and address
def profile(request,shop_id):
    db=connect()
    c=db.cursor()

    shop_ids = get_shopid_list(c)

    if shop_id in shop_ids:
        shop_info = get_shopinfo(request,c,shop_id)
        shop_loc = get_shoploc(request,c,shop_id)
        shop_cord = get_shopcord(c,shop_id)

        context = { 'shop_info':shop_info, 'shop_loc':shop_loc, 'shop_cord':shop_cord}
        return render(request, 'shop/profile.html', context)
    else:
        context={}
        return render(request, 'shop/profile.html', context)

# Displays the information for the current stocks in the shop     
@login_required
def cur_stock(request):
    db=connect()
    c=db.cursor()
    if request.user.is_authenticated:
        
        db=connect()
        c=db.cursor()
        
        shop_id = get_shopid(request,c)
        cur_stock = get_curstock(request,c,shop_id)
        print(cur_stock)
        context = { 'shop_id':shop_id, 'cur_stock':cur_stock }
        return render(request, 'shop/curstock.html', context)

    else:
        context = {}
        return render(request, 'home/loginpage.html', context)

# Displays the license information of the shop
@login_required
def license(request):
    # print(request.injection)
    if request.user.is_authenticated:
        
        db=connect()
        c=db.cursor()
        
        shop_id = get_shopid(request,c)
        shop_license = get_license(request,c,shop_id)
        
        print(shop_license)

        context = {'shop_id':shop_id , 'shop_license':shop_license }
        return render(request, 'shop/license.html', context)
    else:
        context = {}
        return render(request, 'home/loginpage.html', context)

# View for updating the information of the the shop      
@login_required
def update_info(request):
    db=connect()
    c=db.cursor()
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    if request.user.is_authenticated:
        shop_id = get_shopid(request,c)
        cur_shop_info = get_shopinfo(request,c,shop_id)
        cur_shop_loc = get_shoploc(request,c,shop_id)
        if request.method == 'POST':
            q = request.POST.dict()

            update = False
            keys = ["shop_name","owner_name","mob_no","alt_no"]

            for i in range(len(keys)):
                if cur_shop_info[i][1] != q[cur_shop_loc[i][0]]:
                    update = True
                    break

            if update:
                c.execute(
                    """ update shop_info
                        set name = %s, owner_name = %s, mob_no= %s,  alt_no= %s
                        where shop_id = %s """,
                        (*[ q[i] for i in keys ],shop_id,) 
                )
                db.commit()

            update = False
            keys = ["city","district","state"]

            for i in range(len(keys)):
                if cur_shop_info[i][1] != q[cur_shop_loc[i][0]]:
                    update = True
                    break

            if update:
                c.execute(
                    """ update shop_loc
                        set city = %s, district = %s,  state= %s
                        where shop_id = %s """,
                        (*[ q[i] for i in keys ],shop_id,) 
                )
                db.commit()
            
            return redirect(reverse('shop:dashboard'))
                # if q['change_cord']:
                #     return redirect(reverse('update_cord'))
                # else:
                #     return redirect(reverse('dashboard'))

        else:
            context = { 'shop_id':shop_id, 'shop_info':cur_shop_info, 'shop_loc':cur_shop_loc }
            return render(request, 'shop/updateinfo.html', context)
    else:
        context = {}
        return render(request, 'home/login-page.html', context)

# View used for upddating the license information
# of the shop data.
@login_required
def update_license(request):
    db=connect()
    c=db.cursor()
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    if request.user.is_authenticated:
        shop_id = get_shopid(request,c)
        cur_shop_license = get_license(request,c,shop_id)
        if request.method == 'POST':
            q = request.POST.dict()
            print(q)       
            update = False
            keys = [ "license", "drug-license", "ph_id" ,"ph_name","deg","college"]
            
            for i in range(0,2):
                if cur_shop_license[i] != q[keys[i]]:
                    update = True
                    break

            if update:
                c.execute(
                    """ update shop_license
                        set license = %s, dr_license_no = %s
                        where shop_id = %s """,
                        (q['license'],q['drug_license'],shop_id,) 
                )
                db.commit()
            
            update = False
            for i in range(3,5):
                if cur_shop_license[i] != q[keys[i]]:
                    update = True
                    break

            if update:
                c.execute(
                    """ update ph_detail
                        set name = %s, deg = %s, college = %s
                        where ph_id = %s """,
                        (q['ph_name'],q['deg'],q['college'],q['ph_id'],) 
                )
                db.commit()

            return redirect(reverse('shop:dashboard'))
        else:
            context = {'shop_id':shop_id , 'shop_license':cur_shop_license }
            return render(request, 'shop/updatelicense.html', context)

# Main page for updating the stock page of the shop
@login_required
def update_stock(request):
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    db=connect()
    c=db.cursor()
    if request.user.is_authenticated:
        q = request.POST.dict()
        shop_id = get_shopid(request,c)
        if request.method == 'POST':
            if q['submit'] == 'Update':
                return redirect(reverse('shop:cur_stock'))
            else:
                return redirect(reverse('shop:add_med'))
        else:
            cur_stock = get_curstock(request,c,shop_id)
            med_ids = list(cur_stock.keys())
            med_ids.sort()

            heads = [ 'gen_name', 'units', 'price', 'mfg_date', 'exp_date', 'batch']
            context = { 'shop_id':shop_id, 'cur_stock': cur_stock , 'heads':heads, 'med_ids':med_ids}
            return render(request, 'shop/updatestock.html', context)
    else:
        context = {}
        return render(request, 'home/login-page.html', context)

# View for updating the stock details like the price, units ,
# mfg_date and exp_date of the medicine in stock of the shop.
@login_required
def update_med(request):
    db=connect()
    c=db.cursor()
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    med_id = request.GET.get('med_id')

    if request.user.is_authenticated:
        shop_id = get_shopid(request,c)
        keys = [ 'med_id', 'units', 'price','batch', 'mfg_date', 'exp_date']
        if request.method == 'POST':
            q= request.POST.dict()
            
            c.execute(
                """ update avail 
                    set units = %s, price = %s, mfg_date = %s, exp_date = %s, batch = %s
                    where med_id = %s and shop_id = %s """ ,
                    (q['units'],q['price'],q['mfg_date'],q['exp_date'],q['batch'],q['med_id'],shop_id)
            )
            db.commit()
            return redirect(reverse('shop:update_stock'))
        else:
            c.execute(
                """ select gen_name from med_info
                    where med_id = %s """,
                    (med_id,)
            )
            gen_name = c.fetchone()[0]
            print(gen_name)
            c.execute(
                """ select med_id,units,price,batch,mfg_date,exp_date from avail
                    where med_id = %s and shop_id = %s """ ,
                    (med_id,shop_id,)
            )

            res = list(c.fetchone())
            med_details = []
            for i in range(len(keys)):
                med_details.append([keys[i],res[i]])

            med_details[4][1]=str(med_details[4][1])
            med_details[5][1]=str(med_details[5][1])
            print(med_details)

            context = { 'gen_name':gen_name, 'med_details':med_details }
            return render(request,'shop/updatemed.html', context)
    else:
        context = {}

GenMed/templates/shop/addmed.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/addmed.css' %}">
{% endblock %}

<!-- context = { 'shop_id':shop_id, 'shop_info':cur_shop_info, 'shop_loc':cur_shop_loc } -->

{% block body_2 %}
    <section id='addmed-sec'>
        <h1 class='sec-head'>Medicine Details</h1>
        <hr>
        <form action={% url 'shop:add_med' %} method="post">
            {% csrf_token %}
            {% for row in keys|slice:':4' %}
                <p>
                    <label for="{{row}}">{{ row|title }}</label>
                    <input type="text" name="{{row}}" id="{{row}}"" value="">
                </p>
            {% endfor %}
            {% for row in keys|slice:'4:' %}
                <p>
                    <label for="{{row}}">{{ row|title }}</label>
                    <input type="date" name="{{row}}" id="{{row}}"" value="">
                </p>
            {% endfor %}
            <p id='bPara'>
                <input type="submit" value="Update" name='update_button'>
            </p>
        </form>

    </section>
{% endblock %}

GenMed/templates/shop/comment.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/comment.css' %}">
{% endblock %}

<!-- context = { 'shop_id':shop_id, 'shop_info':cur_shop_info, 'shop_loc':cur_shop_loc } -->

{% block body_2 %}
    <section id='addmed-sec'>
        <h1 class='sec-head'>Medicine Details</h1>
        <hr>
        <form action={% url 'shop:comment' %} method="post">
            {% csrf_token %}
                <input type="text" name="title" placeholder='Title...'>
                <input type="text" name="shop_id" placeholder='Shop Id...'>
                <input type="textarea" name="comment" placeholder='Comment...'>
            <p id='bPara'>
                <input type="submit" value="Submit" name='submit'>
                <a href={% url 'shop:home '}> <button id='upBtn'>Cancel</button> </a>
            </p>
        </form>

    </section>
{% endblock %}

GenMed/templates/shop/dashboard.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/dashboard.css' %}">
{% endblock %}

<!-- context = {'shop_id':shop_id , 'shop_loc':shop_loc, 'shop_info':shop_info} -->

{% block body_2 %}
    <section id='info-sec'>
        <h1 class='sec-head'>Basic Info</h1>
        <hr>
        <table>
            <tr>
                <th>Details</th>
                <th>Info</th>
            </tr>
            {% for row in shop_info %}
                <tr>
                    <td class='col1'>{{row.0|title}}:</td>
                    <td class='col2'>{{row.1}}</td>
                </tr>
            {% endfor %}
            <tr>
                <td class='col1'>Shop_Address:</td>
                <td class='col2'>
                    {% for row in shop_loc %}
                        {{row.1}},
                    {% endfor %}
                </td>
            </tr>
        </table>
        <p id='bPara'><a href={% url 'shop:update_info' %}><button id='upBtn'>Update</button></a></p>
    </section>
{% endblock %}

GenMed/templates/shop/home.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/home.css' %}">
{% endblock %}

{% block body_2 %}
    <section id='home_sec'>
            <div class="para">
                    <h1>Why are drug stores imporatant?</h1>
                    <p>Small commercial drug shops and pharmacies are often the first line of health 
                       care in poor countries, especially in rural areas that have very few private 
                       or public clinics. Drug shops and pharmacies, with their convenience, anonymity, 
                       and cost-savings (compared to private physicians), are an important source of 
                       health services, products, and information that is particularly important in 
                       the context of high maternal mortality and morbidity, critical health-worker 
                       shortages, poorly stocked clinics, and high unmet need for family planning </p>
                </div>
        
                <div class='para'>
                    <h1>Where are generic medicine stores?</h1>
                    <p> Generic medicine stores atr those drug stroes or pharmacies which are prescribed
                        to sell generic medicines.
                        A generic drug is a medication created to be the same as an already 
                        marketed brand-name drug in dosage form, safety, strength, route of 
                        administration, quality, performance characteristics, and intended use.
                    <br><br>
                        Due to low awareness of generic medicine in our society, these types of medicine 
                        stores are scarce.However with the effort of the government more and more such shops 
                        are being in different parts of country, specially in rural and impoverished areas
                        in order to provide better healthcare services in these areas. 
                    </p>
                </div>
            <div id='bPara'>
                <a href={% url 'shop:shopcomments' %}> <button class='upBtn'> Show Comments </button> </a>
                <a href={% url 'shop:comment' %}> <button class='upBtn'> Add Comments </button> </a>
            </div>
    </section>
{% endblock %}

GenMed/templates/shop/license.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/license.css' %}">
{% endblock %}



{% block body_2 %}
    <section id='license-sec'>
        <h1 class='sec-head'>License Details</h1>
        <hr>
        <table>
            <tr>
                <th class='t1col1'>Details</th>
                <th class='t1col2'id='last-th'>Info</th>
            </tr>
            {% for row in shop_license|slice:":2" %}
            <tr>
                <td class='t1col1'>{{row.0|title}}:</td>
                <td class='t1col2'>{{row.1}}</td>
            </tr>
            {% endfor %}
        </table>
    </section>
    <section id='ph-detail'>
        <h1 class='sec-head'>Pharmacist Details</h1>
        <hr>
        <table>
            <tr>
                <th class='t2col1'>Details</th>
                <th class='t2col2' id='last-th'>Info</th>
            </tr>
            {% for row in shop_license|slice:"3:" %}
            <tr>
                <td class='t2col1'>{{row.0|title}}:</td>
                <td class='t2col2'>{{row.1}}</td>
            </tr>
            {% endfor %}
        </table>
        <p id='bPara'><a href={% url 'shop:update_license' %}><button id='upBtn'>Update</button></a></p>
    </section>
{% endblock %}

GenMed/templates/shop/shopheader.html
{% extends 'baseheader.html' %}

{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/shopheader.css' %}">

    {% block head_2 %}
    {% endblock %}

{% endblock %}

{% block body %}
    <header class="shop-header">
        <div class="bg-image">
            <h1>GenMed-Project</h1>
            <h3>Search nearby shop here by city or name</h3>
            <div class='container'>
                <div id='form_div'>
                    <form action="{% url 'shop:search' %}" method="get">
                            <p>
                            <input type="text" class='inp' name="tag" list='tags' id="tag" placeholder='Tag...' style='color:black'>
                            <datalist id='tags'>
                                <option value="By Name">Searches by ths shop name</option>
                                <option value="By City">Searches by the city name</option>
                            </datalist>
                            <input type="text" name="param" id="param" class=inp placeholder='Search...' >
                            <input type="submit" value="Search" class='inp' id='subBtn'></p>
                            <p>
                        </form>
                </div>
            </div>
        </div>
    </header>

    <div class='container' id="main">
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-md navbar-expand-sm navbar-expand-xs sticky-top" id='inner-nav'>
                    <!--Links-->
                        <ul class="navbar-nav navbar-left">
                            <li class="nav-item col-sm-4 col-xs-4"><a href={% url 'shop:home' %} class="nav-link">Home</a></li>
                            <li class="nav-item col-sm-4 col-xs-4"><a href={% url 'shop:dashboard' %} class="nav-link">Dashboard</a></li>
                            <li class="nav-item col-sm-4 col-xs-4"><a href={% url 'shop:license' %} class="nav-link">License</a></li>
                            <li class="nav-item col-sm-4 col-xs-4"><a href={% url 'shop:cur_stock' %} class="nav-link">Stocks</a></li>
                        </ul>
            </nav>
        {% endif %}
            {% block body_2 %}
            {% endblock %}
    </div>
{% endblock %}

GenMed/templates/shop/updateinfo.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/updateinfo.css' %}">
{% endblock %}

<!-- context = { 'shop_id':shop_id, 'shop_info':cur_shop_info, 'shop_loc':cur_shop_loc } -->

{% block body_2 %}
    <section id='updateinfo-sec'>
        <form action={% url 'shop:update_info' %} method="post">
            {% csrf_token %}
            <h1 class='sec-head'>Basic Info</h1>
            <hr>
            <!-- {% for key,value in shop_info.items %}
                <p>
                    <label for="{{key}}">{{ key|title }}:</label>
                    <input type="text" name="{{key}}" id="{{key}}" value="{{ value }}">
                </p>
            {% endfor %} -->
            {% for row in shop_info %}
                <p>
                    <label for="{{row.0}}">{{ row.0|title }}:</label>
                    <input type="text" name="{{row.0}}" id="{{row.0}}" value="{{ row.1 }}">
                </p>
            {% endfor %}
            <h1 class='sec-head'>Shop Location</h1>
            <hr>
            {% for row in shop_loc %}
                <p>
                    <label for="{{row.0}}">{{ row.0|title }}:</label>
                    <input type="text" name="{{row.0}}" id="{{row.0}}" value="{{ row.1 }}">
                </p>
            {% endfor %}
            <p id='l-para'>Do you want to update the coordinates of your shop ? &nbsp;&nbsp; <input type="checkbox" name="change_cord"></p>
            <p id='bPara'>
                <input type="submit" value="Update" name='update_button'>
                <a href={% url 'shop:dashboard' %}><button id='upBtn'>Cancel</button></a>
            </p>
        </form>

    </section>
{% endblock %}

GenMed/templates/shop/updatelicense.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/updatelicense.css' %}">
{% endblock %}

{% block body_2 %}
    <section id='updatelicense-sec'>
        <form action={% url 'shop:update_license' %} method="post">
            {% csrf_token %}
            <h1 class='sec-head'>License Details</h1>
            <hr>
            {% for row in shop_license|slice:":2" %}
                <p>
                    <label for="{{row.0}}">{{ row.0|title }}:</label>
                    <input type="text" name="{{row.0}}" id="{{row.0}}" value="{{ row.1 }}">
                </p>
            {% endfor %}
            <h1 class='sec-head'>Pharmacist Details</h1>
            <hr>
            {% for row in shop_license|slice:"3:" %}
                <p>
                    <label for="{{row.0}}">{{ row.0|title }}:</label>
                    <input type="text" name="{{row.0}}" id="{{row.0}}" value="{{ row.1 }}">
                </p>
            {% endfor %}
            <input type="hidden" name="ph_id" value="{{ shop_license.2.1 }}">
            <p id='bPara'>
                    <input type="submit" value="Update" name='update_button'>
                    <a href={% url 'shop:license' %}><button id='upBtn'>Cancel</button></a>
            </p>
        </form>
    </section>
{% endblock %}

GenMed/templates/shop/updatemed.html
{% extends 'shop/shopheader.html' %}

{% load static %}

{% block head_2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/addmed.css' %}">
{% endblock %}

<!-- context = { 'shop_id':shop_id, 'shop_info':cur_shop_info, 'shop_loc':cur_shop_loc } -->

{% block body_2 %}
    <section id='addmed-sec'>
        <h1 class='sec-head'>Medicine Details:</h1>
        <hr>
        <form action={% url 'shop:update_med' %} method="post">
            {% csrf_token %}
                <p>
                    <label for="gen_name">Gen Name:</label>
                    <input type="text" name="gen_name" id="gen_name" disabled value="{{ gen_name }}">
                </p>
                <input type="hidden" name="{{ med_details.0.0 }}" value="{{ med_details.0.1 }}">
            {% for row in med_details|slice:'1:4' %}
                <p>
                    <label for="{{row.0}}">{{ row.0|title }}:</label>
                    <input type="text" name="{{row.0}}" id="{{row.0}}"" value="{{row.1}}">
                </p>
            {% endfor %}
            {% for row in med_details|slice:'4:' %}
                <p>
                    <label for="{{row.0}}">{{ row.0|title }}:</label>
                    <input type="date" name="{{row.0}}" id="{{row.0}}"" value="{{row.1}}">
                </p>
            {% endfor %}
            <p id='bPara'>
                <input type="submit" value="Update" name='update_button'>
            </p>
        </form>

    </section>
{% endblock %}