GenMed/GenMed/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'),namespace='home')),
    path('shop/', include(('shop.urls', 'shop'),namespace='shop')),
    path('medicine/', include(('medicine.urls', 'medicine'),namespace='medicine')),
]

GenMed/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.logIn, name='logIn'),
    path('logout/',views.logOut, name='logOut'),
    path('register/',views.register, name='register'),
    path('createshop/',views.createshop, name='create_shop'),
    path('sqlerror/', views.sqlerror, name = 'sqlerror')
]

GenMed/home/models.py
from django.db import models

# Create your models here.

GenMed/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
import MySQLdb

#this file includes function for sql queries used by multiple views.
from GenMed.mysql import *

def is_valid_email(email):
    return True

# View for displaying the homepage in the home app
def home(request):
    context = {}
    return render(request, 'home/home.html', context)

def sqlerror(request):
    return render(request, 'home/sqlerror.html', context = {})

# View for logging in 
def logIn(request):
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    db=connect()
    c=db.cursor()
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            print('1.',str(user))
            return redirect(reverse('shop:dashboard'))
        else:    
            context = { 'error':True }
            return render(request, 'home/loginpage.html', context)
    else:
        get_userlist(request,c)
        context = { 'error':False }
        return render(request, 'home/loginpage.html', context)

# View for logging out
def logOut(request):
    try:
        logout(request)
    except ValueError:
        pass
    return redirect(reverse('home:home'))

# View for registering
def register(request):
    db=connection
    c=db.cursor()
    userlist = get_userlist(request,c)
    if request.method=='POST':
        q = request.POST.dict()
        print(q)
        if q['password'] != q['cnf_password']:
            err = "Passwords don't match"
            return render(request, 'home/register.html', context= { 'err': err })
        elif not is_valid_email(q['email']):
            err = "Invalid email"
            return render(request, 'home/register.html', context= { 'err': err })
        elif q['username'] in userlist:
            err = "Username already taken"
            return render(request, 'home/register.html', context= { 'err': err })
        else:
            c.execute(
                """ INSERT into shop(username,email,passwd) 
                    values (%s,%s,%s) """,
                    (q['username'],q['email'],q['password'])
            )
            db.commit()
            p = User(username=q['username'],password=q['password'])
            p.save()
            login(request,p)
            return render(request, 'home/createshop.html', context = {})
    else:
        context = { 'userlist':userlist }
        return render(request, 'home/register.html', context)

# View for creating a shop object
@login_required
def createshop(request):
    db=connect()
    c=db.cursor()
    # if request.injection:
    #     return redirect(reverse('home:sqlerror'))
    if request.user.is_authenticated:
        if request.method == 'POST':
            q = request.POST.dict()
            shop_id = get_max_shopid(request,c)+1
            user_id = get_userid_by_name(request,c)
            
            # insert into shop_info
            c.execute(
                """ INSERT into shop_info(shop_id,name,owner_name,
                    mob_no,alt_no,license,user_id) values(%s,%s,%s,%s,%s,%s,%s) """,
                    (shop_id,q['shop_name'],q['owner_name'],
                        q['mob_no'],q['alt_no'],q['license'],user_id)
            )
            db.commit()
            
            # insert into the pharmacist table the pharmacist details
            c.execute(
                """ INSERT into ph_detail(name,deg,college)
                    values(%s,%s,%s) """,
                    (q['ph_name'],q['ph_deg'],q['ph_college'])
            )
            db.commit()

            # get the ph_id of the saved pharmacist
            c.execute(
                """ SELECT ph_id
                    from ph_detail
                    where name = %s and deg = %s and college = %s """,
                    (q['ph_name'],q['ph_deg'],q['ph_college'])
            )
            
            ph_id=str(c.fetchone()[0])
            
            # inserts information in the shop_license table
            c.execute(
                """ INSERT into shop_license(shop_id,ph_id,license,dr_license_type,dr_license_no)
                    values(%s,%s,%s,%s,%s) """,
                    (shop_id,ph_id,q['license'],q['drug_license_type'],q['drug_license'])
            )
            db.commit()

            # insert into the shop_location table
            c.execute(
                """ INSERT into shop_loc(shop_id,lat,lon,
                    state,district,city) values(%s,%s,%s,%s,%s,%s) """,
                    (shop_id,q['lat'],q['lon'],
                     q['state'],q['district'],q['city'])
            )
            db.commit()
            return redirect(reverse('shop:dashboard'))
        else:
            context = {}
            return render(request, 'home/createshop.html', context)
    else:
        context = {}
        return render(request, 'home/createshop.html', context)

GenMed/templates/home/createshop.html
{% extends 'home/homeheader.html' %}

{% load static %}
{% block head2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/createshop.css' %}">
{% endblock %}


{% block body2 %}
    <div class='container'>
      <section class="features" id="register-sec">
        <h1 style="text-align: center">Register with the GenMed-Project</h1>
        <hr>
        <form id="regForm" action={% url 'home:create_shop' %} method="POST">
            {% csrf_token %}
            <div class='parts'> <h3 class='tab-head'>Shop Info</h3> 
              <p><input class='inp' placeholder="Shop Name..."  name="shop_name"></p>
              <p><input class='inp' placeholder="Owner Name..."  name="owner_name"></p>
              <p><input class='inp' placeholder="Mob No..."  name="mob_no"></p>
              <p><input class='inp' placeholder="Alt No..."  name="alt_no"></p>
            </div>
            <div class="parts"> <h3 class='tab-head'>License Detail</h3> 
              <p><input class='inp' placeholder="License..."  name="license"></p>
              <p><input class='inp' placeholder="Drug License..."  name="drug_license"></p>
              <p><input class='inp' placeholder="Drug License Type..."  name="drug_license_type"></p>
            </div>
            <div class="parts"> <h3 class='tab-head'>Pharmacist Detail</h3> 
              <p><input class='inp' placeholder="Name..."  name="ph_name"></p>
              <p><input class='inp' placeholder="Degree..."  name="ph_deg"></p>
              <p><input class='inp' placeholder="College..."  name="ph_college"></p>
            </div>
            <div class="parts"> <h3 class='tab-head'>Address</h3>
                <p><input class='inp' placeholder="City..."  name="city"></p>
                <p><input class='inp' placeholder="District..."  name="district"></p>
                <p><input class='inp' placeholder="State..."  name="state"></p>
                <p><input type="text" name="lat" id="lat" placeholder="Latitude...">
                   <input type="text" name="lon" id="lon" placeholder="Longitude...">
                   <input type="button" class='inp' id='locBtn' onclick=getLocation() value='Fetch Location'></p>
            </div>
            <p id='bt'><input class='inp' type="submit" value="Submit" name='submit_btn' id="subBtn"></p>
          </form>
    </section>
    </div>
          
          <script src="{% static 'home/createshop.js' %}"></script>
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
{% endblock %}

GenMed/templates/home/home.html
{% extends 'home/homeheader.html' %}

{% load static %}
{% block head2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/homepage.css' %}">
{% endblock %}

{% block header %}
    <button action="#description"><p>READ MORE  </p> <i class="fa fa-angle-down" aria-hidden="true"></i></button>
{% endblock %}

{% block body2 %}
    <section id="description" class="features">
        <div class="container">
            <div class="row m-b-lg">
                <div class="col-lg-12 text-center">
                    <h1 style="font-size:30px">About Us</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8 text-center wow zoomIn m-t-lg m-b-lg" id="des-para">
                    <p>
                        <span>
                            This project is made with a simple aim in the mind - to make healthcare services affordable.<br>
                            GenMed-Project is aimed at connecting the generic medicine shops to the consumers.
                            There are many generic medicine shops in each city some owned and run by the govt. and other by individuals
                            But people don't know about these stores and thus this alternative to high cost medications never strikes in their mind
                            Here what i have tried to done is to make a web app that helps people find information related to generic
                            medicine - like their branded names, shops which keep generic medicine and helps locate nearby shops where
                            a particular generic medicine is available. <br><br>
                        </span>
                    </p>
                    <p>
                        <span>
                            A generic medicine is a medication created to be the same as an already 
                            marketed brand-name drug in dosage form, safety, strength, route of 
                            administration, quality, performance characteristics, and intended use. 
                            These similarities help to demonstrate bioequivalence, which means 
                            that a generic medicine works in the same way and provides the same
                            clinical benefit as its brand-name version. In other words, you can 
                            take a generic medicine as an equal substitute for its brand-name counterpart.
                        </span>
                    </p>    
                    <p>
                        <span>
                            But due to lack of awareness in our society most people don't know about generic medicines.
                            Although it doesn't matter for the people who are well off but for the lower section of society
                            who often give up on healthcare and treatment due to the high cost of medication and equipments
                            these medicines can be a life saver.
                        </span>
                    </p>
                    <p>
                        <span>
                
                        </span>
                    </p>
                    </div>
            </div>
        </div>
    </section>
{% endblock %}

GenMed/templates/home/homeheader.html
{% extends 'baseheader.html' %}
{% load static %}
    {%  block head %}
        <link rel="stylesheet" type="text/css" href="{% static 'home/homeheader.css' %}">
        {% block head2 %}
        {% endblock %}
    {% endblock %}


</head>
{% block body %}
    <header>
        <div class="bg-image">
            <h1>GenMed-Project</h1>
            <h3>Cheaper . Reliable . Effective</h3>
            {% block header %}
            {% endblock %}
        </div>
    </header>

    {% block body2 %}
    {% endblock %}

{% endblock %}

GenMed/templates/home/loginpage.html
{% extends 'home/homeheader.html' %}

{% load static %}
{% block head2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/loginpage.css' %}">
{% endblock %}

{% block body2 %}
    <section id="login-section">
            <div class="col-lg-4 col-md-6" id="login-box">
                <div class="fields"> 
                        <h1>Login</h1>
                </div>
                {% if error%}
                    <p>Username/Password is incorrect</p>
                {% endif %}
                <form action={% url 'home:logIn' %} method="POST" id="login-form">
                    {% csrf_token %}
                    <input type="text" placeholder="Username" class="login-input" name="username"/>
                    <input type="password" placeholder="Password" class="login-input" name="password"/>
                    <input type="submit" value="Login" class="login-button" />
                </form>
            </div>
    </section>
{% endblock %}

GenMed/templates/home/register.html
{% extends 'home/homeheader.html' %}

{% load static %}
{% block head2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/register.css' %}">
{% endblock %}


{% block body2 %}
    <div class='container'>
      <section class="features" id="register-sec">
        <h1 style="text-align: center">Register with the GenMed-Project</h1>
        <hr>
        <form id="regForm" action={% url 'home:register' %} method="POST">
            {% csrf_token %}
              <p><input placeholder="Username..."  name="username"></p>
              <p><input type="email" placeholder="E-mail..."  name="email"></p>
              <p><input type="password" placeholder="Password..."  name="password" id='password'></p>
              <p><input type="password" placeholder="Confirm Password..."  name="cnf_password" id='cnf_password'></p>
              <p><span id="#err">{{ err }}</span></p>
              <p id='bt'><input type="submit" value='Register' name='register' id='subBtn'></p>
          </form>
    </section>
    </div>
{% endblock %}

GenMed/templates/home/sqlerror.html
{% extends 'home/homeheader.html' %}

{% load static %}
{% block head2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/sqlerror.css' %}">
{% endblock %}

{% block body2 %}
    <section id="sqlerror">
            <div class="col-lg-4 col-md-6 alert alert-danger" >
                <p id ='#msg'>HeHe! Caught You. :P</p>
                <a href={% url 'home:home' %}><button id='homeBtn'>Go Home!</button></a>
            </div>
    </section>
{% endblock %}